# Generated by Django 5.1.1 on 2024-09-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagem',
            new_name='image',
        ),
    ]
